### ISSUE TITLE
Использование сервера прослойки

### ISSUE THREAD

**Issue by lyubitelev** [rbkmoney/docs#107]
Здравствуйте, меня интересует возможна ли следующий алгоритм сотрудничества с Вами:
есть несколько интернет магазинов с разными доменами и ссылками оплаты и все они принадлежат одному ООО, мы хотим реализовать прослойку которая бы могла администрировать подключения этих магазинов и их товаров/услуг, а так же формировала ссылку оплаты для пользователя на основе выбранных им товаров/услуг. Алгоритм следующий, пользователь заходит в магазин, выбирает что купить, покупает, запрос поступает в прослойку, она формирует ссылку на покупку в ваш сервис, пользователь ее получает и перенаправляется в ваш сервис для осуществления покупки.
Возможно ли такое?
Спасибо

**Comment by antonlva** [comment]
Возможно, это и есть основная схема работы с нами. Заполняйте заявку на подключение на https://rbk.money/ и вам все подключат и покажут как интегрироваться.

**Comment by Kachit** [comment]
Здравствуйте, у нас планируется аналогичная схема взаимодействия с вашим сервисом, на данный момент происходит интеграция, скажите, как с вами можно связаться по этому вопросу ?

**Comment by antonlva** [comment]
Уточните, что у вас за вопрос?

**Comment by Kachit** [comment]
у нас накопилось несколько вопросов по поводу интеграции, хотелось бы обсудить их не на публике

**Comment by antonlva** [comment]
У вас менеджер по подключению уже есть? Если нет, напишите мне в телеграм @anton_lva, я создам для вас закрытый чат поддержки.
