### ISSUE TITLE
Unauthorized 401

### ISSUE THREAD

**Issue by emiloserdov** [rbkmoney/docs#108]
Здравствуйте. Делаю реквест через АПИ на создание одноразового токена платежного средства, подставляю ключ в заголовок Authorization: Bearer + ключ. Возвращается ошибка 401, хотя предыдущий запрос на создание инвойса такого же вида завершается со статусом 201. 
Ниже лог запроса и ответа. 
Запрос::::
ok:POST /v2/processing/payment-resources HTTP/1.1
Host: api.rbk.money
Accept: application/json
Authorization: Bearer ***********UIiwia2lkIiA6ICIzaG14MU9*********
Content-Type: application/json;charset=utf-8
X-Request-Id: c62ab29e-773a-4d09-bcd0-c168310

{"paymentTool":{"paymentToolType":"CardData","cardNumber":"5555555555554444","expDate":"12/20","cvv":"123","cardHolder":"qwe qwe"},"clientInfo":{"fingerprint":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36","ip":""}} 

Ответ:::
INFO[1900] dumpResponse ok:HTTP/2.0 401 Unauthorized
Content-Length: 0
Content-Type: application/json; charset=utf-8
Date: Mon, 15 Apr 2019 13:39:23 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

**Comment by antonlva** [comment]
Это сработала защита от общедоступной публикации API-ключа, его можно использовать только для сервер-сервер взаимодействия. А для авторизации создания платежного токена надо использовать invoiceAccessToken, он возвращается при создании инвойса [createInvoice()](https://developer.rbk.money/api/#operation/createInvoice) или при отдельном вызове метода [createInvoiceAccessToken](https://developer.rbk.money/api/#operation/createInvoiceAccessToken).

**Comment by emiloserdov** [comment]
То есть его нужно вставлять в хедер Authorization: Bearer {invoiceAccessToken}?
Правильно я понимаю?

**Comment by emiloserdov** [comment]
В АПИ это описано по-другому:
https://developer.rbk.money/api/#operation/createPaymentResource
AUTHORIZATIONS:
bearer

**Comment by emiloserdov** [comment]
????????
Так же, почему в АПИ, при использовании метода CreatePayment при 
 payerTyperequired string Тип платежного средства PaymentResourcePayer
не указано, что структура paymentToolDetails обязательна? И еще неясно, какое значение нужно ставить в поле "tokenProvider", которое тоже оказывается необходимым, хотя это нигде не указано?

Запрос::::
{"flow":{"type":"PaymentFlowHold","onHoldExpiration":"cancel"},"payer":{"payerType":"PaymentResourcePayer","paymentToolToken":"e****************************hbiI6IjQ0NDQiLCJtZXRhZGF0YSI6eyJjb20ucmJrbW9uZX**********************************************lwZSI6ImJhbmtfY2FyZCJ9","paymentToolDetails":{"detailsType":"PaymentToolDetailsBankCard","cardNumberMask":"555555******4444","bin":"555555","lastDigits":"4444","paymentSystem":"mastercard","tokenProvider":"applepay"},"contactInfo":{"email":"testtesttest@gmail.com","phoneNumber":"+79991231230"}}} 

Ответ????????::::
INFO[0061] dumpResponse ok:HTTP/2.0 500 Internal Server Error
Content-Length: 2069
Content-Type: text/plain; charset=utf-8
Date: Mon, 15 Apr 2019 15:37:37 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

█▄░░░░░░░░░░░░░░░░░░░░░░░░▄▄███
███▄░░░░░░░░░░░░░░░░░░░░▄██████
█████▄░░░░░░░░░░░░░░░░░▄███████
███████▄░░░░▄▄▄▄▄░░░░▄█████████
█████████▄▀▀░░░░░▀▀▀▄██████████
▀█████▀░░░░░░░░░░░░░░▀████████░
░▀██▀░░░░░░░░░░░░░░░░░░░▀████▌░
░░██░░░░░░░░░░░░░░░░░░░░░░███░░
░░█▀░░░░░░░░░░░░░░░░░░░░░░░██░░
░░█░░▄████▄░░░░░▄████▄░░░░░░█░░
░░█░░█▐▄█▐█░░░░░█▐▄█▐█░░░░░░█▄░
░░█░░██▄▄██░░░░░██▄▄██░░░░░░░█░
░▐▌░░░░░░░░░░░░░░░░░░░░░░░░░░▐▌
░▐▌░░░░░░░▀▄▄▄▄▀░░░░░░░░░░░░░▐▌
░▐▌░░░░░░░░░▐▌░░░░░░░░░░░░░░░▐▌
░▐▌░░░░░░░▄▀▀▀▀▄░░░░░░░░░░░░░▐▌
░░█▄░░░░░▀░░░░░░▀░░░░░░░░░░░░█▌
░░▐█▀▄▄░░░░░░░░░░░░░░░░░░▄▄▀▀░█
░▐▌░░░░▀▀▄▄░░░░░░░░▄▄▄▄▀▀░░░░░█
░█░░░░░░░░░▀▀▄▄▄▀▀▀░░░░░░░░░░░█
▐▌░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
▐▌░░░░░░░░░░░░░░░░░░░░░░░░░░░░█

**Comment by antonlva** [comment]
- авторизация метода createPaymentResource должна производится с помощью отдельного ключа, формат заголовка остается таким же: Authorization: Bearer {IAT}. Мы добавили это уточнение в описание протокола.
- структура paymentToolDetails обязательна только если вы используете токенизированные средства оплаты, такие как GooglePay. Для обычных платежей она не нужна, почему вы подумали, что это так?
- необходимость `tokenProvider` указана в swagger-спецификации и корректна в протоколе. Текущая версия визуализации стороннего проекта ReDoc не отображает этот уровень вложенности, мы знаем про этот баг.

**Comment by antonlva** [comment]
Для облегчения понимания пример вызова метода создания двустадийного платежа:

```bash
curl -X POST \
  https://api.rbk.money/v2/processing/invoices/19Ff9ZuPeDY/payments \
  -H 'Authorization: Bearer {IAT}' \
  -H 'Content-Type: application/json; charset=utf-8' \
  -H 'X-Request-ID: 1555343579' \
  -H 'cache-control: no-cache' \
  -d '{
  "flow": {
    "type": "PaymentFlowHold",
    "onHoldExpiration": "cancel"
  },
  "payer": {
  	  "payerType": "PaymentResourcePayer",
	  "paymentToolToken":"{PTT}",
	  "contactInfo":
	    {
	      "email":"test@test.com",
	      "phoneNumber":"9876543210"
	    }
  }
}'
```

**Comment by emiloserdov** [comment]
Все еще ошибка, делаю все по примеру 

INFO[0003] dumpReq ok:POST /v2/processing/invoices/19H0bBu0bfU/payments HTTP/1.1
Host: api.rbk.money
Accept: application/json
Authorization: Bearer ---------------------4MDAwIiwiaHR0cHM6Ly9kYXNoYm9hcmQucmJrLm1vbmV5Il0sInJlc291cmNlX2FjY2VzcyI6eyJjb21tb24tYXBpIjp7InJvbGVzIjpbImludm9pY2Vz----------------------
Content-Type: application/json;charset=utf-8
X-Request-Id: d120a7db-c7c4-47cc-8d1e-d3c2d70

{"flow":{"type":"PaymentFlowHold","onHoldExpiration":"cancel"},"payer":{"payerType":"PaymentResourcePayer","paymentToolToken":"----------sInBheW1lbnRfc3lzdGVtIjoibWFzdGVyY2F---------------------","contactInfo":{"email":"testtesttest@gmail.com","phoneNumber":"+79991231230"}}} 
INFO[0003] dumpResponse ok:HTTP/2.0 500 Internal Server Error
Content-Length: 2069
Content-Type: text/plain; charset=utf-8
Date: Tue, 16 Apr 2019 11:17:40 GMT
Server: nginx
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

█▄░░░░░░░░░░░░░░░░░░░░░░░░▄▄███
███▄░░░░░░░░░░░░░░░░░░░░▄██████
█████▄░░░░░░░░░░░░░░░░░▄███████
███████▄░░░░▄▄▄▄▄░░░░▄█████████
█████████▄▀▀░░░░░▀▀▀▄██████████
▀█████▀░░░░░░░░░░░░░░▀████████░
░▀██▀░░░░░░░░░░░░░░░░░░░▀████▌░
░░██░░░░░░░░░░░░░░░░░░░░░░███░░
░░█▀░░░░░░░░░░░░░░░░░░░░░░░██░░
░░█░░▄████▄░░░░░▄████▄░░░░░░█░░
░░█░░█▐▄█▐█░░░░░█▐▄█▐█░░░░░░█▄░
░░█░░██▄▄██░░░░░██▄▄██░░░░░░░█░
░▐▌░░░░░░░░░░░░░░░░░░░░░░░░░░▐▌
░▐▌░░░░░░░▀▄▄▄▄▀░░░░░░░░░░░░░▐▌
░▐▌░░░░░░░░░▐▌░░░░░░░░░░░░░░░▐▌
░▐▌░░░░░░░▄▀▀▀▀▄░░░░░░░░░░░░░▐▌
░░█▄░░░░░▀░░░░░░▀░░░░░░░░░░░░█▌
░░▐█▀▄▄░░░░░░░░░░░░░░░░░░▄▄▀▀░█
░▐▌░░░░▀▀▄▄░░░░░░░░▄▄▄▄▀▀░░░░░█
░█░░░░░░░░░▀▀▄▄▄▀▀▀░░░░░░░░░░░█
▐▌░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
▐▌░░░░░░░░░░░░░░░░░░░░░░░░░░░░█

**Comment by antonlva** [comment]
Покажите, какую структуру вы передаете в createPaymentResource()?

**Comment by emiloserdov** [comment]
такого вида
```
cpr := CreatePaymentResource{
		PaymentTool: PaymentTool{
			PaymentToolType: "CardData",
			CardNumber:      card.CardNumber,
			CardHolder:      card.CardHolder,
			Cvv:             card.Cvv,
			ExpDate:         card.ExpDate,
		},
		ClientInfo: ClientInfo{
			Fingerprint: clientFingerPrint,
		},
	}
```
Заполнена таким образом::
```
{
  "paymentTool": {
    "paymentToolType": "CardData",
    "cardNumber": "5555555555554444",
    "expDate": "12/20",
    "cvv": "123",
    "cardHolder": "qwe qwe"
  },
  "clientInfo": {
    "fingerprint": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
    "ip": ""
  }
} 
```

**Comment by antonlva** [comment]
В ответе вызова этого метода также возвращается структура `paymentSession`, передайте ее в метод вызова платежа по аналогии

```bash
curl -X POST \
  https://api.rbk.money/v2/processing/invoices/{INVOICE_ID}/payments \
  -H 'Authorization: Bearer {IAT}' \
  -H 'Content-Type: application/json; charset=utf-8' \
  -H 'X-Request-ID: 1555417451' \
  -H 'cache-control: no-cache' \
  -d '{
  "flow": {
    "type": "PaymentFlowHold",
    "onHoldExpiration":"cancel"
  },
  "payer": {
  	  "payerType": "PaymentResourcePayer",
	  "paymentToolToken":"{PTT}",
	  "paymentSession":"{PS}",
	  "contactInfo":
	    {
	      "email":"test@test.com",
	      "phoneNumber":"9876543210"
	    }
  }
}'
```

**Comment by emiloserdov** [comment]
Все заработало, спасибо.
Поставьте, пожалуйста, в АПИ пометку, что  "paymentSession" поле обязательно. Сейчас оно значится как необязательное. 
![image](https://user-images.githubusercontent.com/45174211/56283139-8716b600-6119-11e9-9de0-3ae38960ca59.png)

**Comment by antonlva** [comment]
Да, это баг, только не в документации, а в реализации обработчика, мы его поправим. Спасибо, что помогли найти.
