### ISSUE TITLE
Ошибка при отправке webhook`а

### ISSUE THREAD

**Issue by Kachit** [rbkmoney/docs#109]
Ошибка при отправке webhook`а, передается заголовок **CONTENT_TYPE**: application/json; charset=utf-8 вместо **content-type** в результате все содержимое тела запроса отображается как данные из формы, хотя у вас в документации написано что приходит json

**Comment by antonlva** [comment]
У нас такие заголовки не устанавливаются и не отправляются. Наш заголовок может выглядеть и выглядит только так:

```bash
Content-Type: application/json; charset=utf-8
```

Проверяйте свои настройки, может вы за каким-то fastcgi сидите, который неправильно настроен.
