### ISSUE TITLE
Оплата в режиме холда

### ISSUE THREAD

**Issue by SergeGusev** [rbkmoney/docs#115]
Коллеги, мне кажется, было бы удобно иметь ещё один статус инвойса - средства захолдированы на карте. 

И, похоже, нет никакого варианта, чтобы через API понять, было ли вообще успешное холдирование средств - ни getInvoiceByID ни getInvoiceEvents не возвращают эту информацию. 

Как выкручиваться? Мне нужно знать, был ли успешным холд.

**Comment by antonlva** [comment]
У счета к оплате, или инвойса, не может быть статуса "захолдирован". Такой статус может быть у платежа, который запускается внутри этого инвойса и он называется `processed`.

https://developer.rbk.money/api/#operation/createPayment
