### ISSUE TITLE
Не получается сделать описание заказа построчно

### ISSUE THREAD

**Issue by SergeGusev** [rbkmoney/docs#116]
Делаю через JS API. Пробовал передавать так:

`description: 'Первый продукт <br/> Второй продукт',`

и так:

`description: 'Первый продукт \n  Второй продукт',`

Не помогает. Есть вариант задать список продуктов, каждый из которых будет показан в новой строке?

**Comment by antonlva** [comment]
Описание и не получится, это поле имеет ограничения в одну строку и 255 символов в силу гайдлайнов UX/UI.

Для описания заказа в виде списка продуктов используйте структуру `cart` объекта `invoice`. Также пригодна для отправки данных в ККТ, включая налоговую ставку.

https://developer.rbk.money/api/#operation/createInvoice

**Comment by SergeGusev** [comment]
Антон, о какой **одной** строке идёт речь? Возможно, мы говорим про разные вещи. Откройте пример чекаута - https://developer.rbk.money/#checkout . Я говорю не про _Резиновую уточку_, а об _Очень важной вещи_. Там штук 8 позиций свободно влезут построчно и будут вполне уместны в поле под заголовком Order details.

**Comment by antonlva** [comment]
Я понимаю о чем вы. Давайте попробую разъяснить нашу позицию по UX.

Чекаут - это форма оплаты _уже собранной_ корзины, например в интернет-магазине. 

Корзина - это бизнес-процесс мерчанта, который происходит до формирования формы оплаты. Если мы говорим об универсальной форме оплаты, чем любой чекаут является, то он не должен дублировать функциональность корзины на сайте. Потому что в корзине может быть потенциально неограниченное количество позиций, ведь никто не запретит мне купить 100 товаров или больше?

Поэтому поля чекаута должны отображать связь с этой корзиной, например:

Название товара: "Интернет-магазин megastore.ru"
Описание товара: "Оплата заказа №1488"

Понимаете что я имею в виду?

**Comment by SergeGusev** [comment]
Антон, ваша позиция понятна. 

Но у заказчика свой вкус и своя правда, которая тоже имеет право на жизнь. Переубеждать его - дело неблагодарное. Но объяснить, что это технически невозможно, вполне возможно. 

Если вы сейчас акцентированно подтвердите, что построчный вывод информации в поле Order description невозможен - будем считать этот вопрос закрытым и искать другое решение.

**Comment by antonlva** [comment]
Мы не будем менять наш чекаут, чтобы в поле описания можно было выводить большие списки товаров, исходя из наших представлений о UX чекаута.
