### ISSUE TITLE
Вопрос по отмене инвойса

### ISSUE THREAD

**Issue by SergeGusev** [rbkmoney/docs#119]
Добрый день. 

Отрабатываю отмену заказа. Если я просто отменяю платёж, то сам инвойс остаётся в статусе "Оплачен", мне это не нравится. Хочу после отмены заказа перевести инвойс в режим "Отменён", но получаю при этом ошибку. Вот логи:

Отмена платежа:

`2019-09-15 21:44:03.0618||DEBUG|RbkMoneyLogger|RbkMoney request: 637041806421328345 : https://api.rbk.money/v2/processing/invoices/1DLnjihZSqW/payments/1/refunds : {"reason":"Платеж отменен","invoiceID":30000} |url: |action: `

`2019-09-15 21:44:03.4793||DEBUG|RbkMoneyLogger|RbkMoney response: 637041806421328345 : OK : {"amount":30000,"createdAt":"2019-09-15T18:44:03.371165Z","currency":"RUB","id":"100","reason":"Платеж отменен","status":"pending"} |url: |action: 
`
Аннулирование инвойса:

`2019-09-15 21:44:18.9598||DEBUG|RbkMoneyLogger|RbkMoney request: 637041806499861299 : https://api.rbk.money/v2/processing/invoices/1DLnjihZSqW/rescind : {"reason":"Платеж отменен"} |url: |action: `

`
2019-09-15 21:44:19.2845||ERROR|RbkMoneyLogger|System.Exception: RbkMoney response: 637041806499861299 : BadRequest : {"code":"invalidInvoiceStatus","message":"Invalid invoice status"} System.Exception: RbkMoney response: 637041806499861299 : BadRequest : {"code":"invalidInvoiceStatus","message":"Invalid invoice status"}|url: |action: 
`

Собственно, вопрос - что не так со статусом инвойса и как правильно его отменить?

**Comment by antonlva** [comment]
Рефанды никак статус инвойса не меняют. Он всегда будет в статусе "оплачен" или "погашен" если однажды перешел в него.

**Comment by SergeGusev** [comment]
То есть вот эта схема состояний инвойса - https://developer.rbk.money/api/#tag/Invoices - неактуальна и в статус Refunded попасть нельзя?

А что тогда делает команда https://developer.rbk.money/api/#operation/rescindInvoice ?

**Comment by antonlva** [comment]
Рефанды бывают у платежа. Выставленный счет к оплате не рефандится, в этом нет смысла.

Команда "погасить инвойс" означает погашение выставленного счета к оплате.
