### ISSUE TITLE
Дробное количество товара

### ISSUE THREAD

**Issue by Rostov85** [rbkmoney/docs#138]
Если у товара дробное количество, то выдает ошибку 401, response по API выдает массив следующего содержания, указывая на неверный формат quantity. В значении менял тип переменной, менял точки на запятые в кол-ве и пр., все безрезультатно
`
[response] => Array
        (
            [http_code] => 400
            [body] => {"code":"invalidRequest","message":"Request parameter: InvoiceParams, error type: schema_violated, description: Wrong format. Path to item: cart[0].quantity"}
            [error] => 0
        )
`

**Comment by antonlva** [comment]
Дробную нельзя передавать, валидатор протокола ожидает целые числа. Как обходной путь можем предложить указывать не `"Яблоки, кг": 0.5`, а `"0,5 кг яблок": 1`.

**Comment by Rostov85** [comment]
Странно конечно. Другие системы оплаты поддерживают. Валидатор можно и изменить, просто на проверку текста, было бы желание. А дробно числа - это тоже число, как ни крути. Ладно, клиент сказал убирать RBK. 
И заметка. Ваш модуль под Opencart не работает с версией opencart 2.3, пришлось собственноручно допиливать. Хотя заявлена поддержка 2.x

--
Отправлено из Mail.ru для Android среда, 17 февраля 2021г., 19:29 +03:00 от Anton Kuranda  notifications@github.com :

**Comment by antonlva** [comment]
Спасибо за обратную связь, учтем ваши замечания!
