### ISSUE TITLE
Как организовать автоплатеж?

### ISSUE THREAD

**Issue by Feduch** [rbkmoney/docs#57]
Добрый день!

Ознакомился с API, не ясно как после первой оплаты запустить автоплатежи. Понимаю, что запустить автоплатеж нужно на своей стороне, но какая последовательность шагов не понятна.

Подскажите, последовательность, спасибо!

**Comment by antonlva** [comment]
Добрый!

В версии v1 (актуальной на 2018-02-28) последовательность следующая:

1. https://rbkmoney.github.io/api/#operation/createCustomer - создаем кастомера
2. https://rbkmoney.github.io/docs/integrations/checkout/#_3- отдаем плательщику чекаут с опцией привязки карты
2.1 Плательщик вводит карточные данные, с него списывается проверочный платеж, который возвращается
3. https://rbkmoney.github.io/api/#operation/getBinding - поллим статус привязки
3.1. https://rbkmoney.github.io/webhooks-events-api/#operation/notifyWebhookEvent - опционально ждем вебхук по статусу привязки
4. С бекенда создаем инвойсы и запускаем https://rbkmoney.github.io/api/#operation/createPayment платежи передавая в них ID кастомера вместо карточных данных.

**Comment by Feduch** [comment]
1,2,3 пункты использовать когда новый клиент, т.е. первая оплата, верно?
На бекенде сохраняем ID кастомера, после упешной оплаты и привязки.

4 пункт используем уже для всех последующих платежей, верно?

**Comment by antonlva** [comment]
> 1,2,3 пункты использовать когда новый клиент, т.е. первая оплата, верно?

Все верно! Это процесс т.н. привязки карты, он нужен для того, чтобы удостовериться, что плательщик как минимум владеет всеми данными карты и может успешно пройти 3D-Secure.

> 4 пункт используем уже для всех последующих платежей, верно?

Да, можем беспрепятственно инициировать списания с бекенда, уже без участия плательщика.

**Comment by Feduch** [comment]
Для отключения автоплатежа:
1. Отключаем на бекенде
2. Удаляем клиента с помощью deleteCustomer 

На вашей стороне 2 пункта достаточно?

**Comment by antonlva** [comment]
Да, этого достаточно.
