### ISSUE TITLE
Как получить список всех Customers?

### ISSUE THREAD

**Issue by Feduch** [rbkmoney/docs#67]
Добрый день!

На сайте используем автоплатежи. Для одного пользователя потеряли его customerID, из-за этого не можем отключить ему автоплатеж. 

Подскажите как получить список customerID наших клиентов?

**Comment by antonlva** [comment]
Привет! Ответ на этот вопрос мы не можем обсуждать публично, поскольку может быть раскрыта чувствительная информация касающаяся ваших плательщиков. Обратитесь, пожалуйста, на support@rbkmoney.com, там дадут ответ в почте или опционально в телеграм-чате.
