### ISSUE TITLE
Templateaccesstoken

### ISSUE THREAD

**Issue by isorbon** [rbkmoney/docs#76]
Здравствуйте уважаемые разработчики, вопрос такой, могу ли я через webhook получить уведомления о платежах если я использую template инвойс, и в каком виде данные из webhook будут переходить мне ?

**Comment by isorbon** [comment]
Еще каким образом безопаснее можно воспользоваться вашим api. Вы же jwt используете если кто то схватит jwt то мне кранты. То есть мне curl использовать на стороне сервера или ajax на стороне клиента?

**Comment by antonlva** [comment]
Здравствуйте.

Уведомления будут приходить согласно спецификации https://webhooks.developer.rbk.money/ независимо от того, каким способом был создан инвойс.

Для безопасности главное не забывать, что на беке надо использовать API-key, а на фронт отдавать [invoiceAccessToken](https://v2.api.developer.rbk.money/#operation/createInvoiceAccessToken).

**Comment by isorbon** [comment]
Антон, добрый ночи, с этим решил вопрос, спасибо за ответ ) Нашел пример у вас на сайте и там 

// Достаем сигнатуру из заголовка и декодируем
$signatureFromHeader = get_signature_from_header($_SERVER['HTTP_CONTENT_SIGNATURE']);
и у меня получился так 
Undefined index: HTTP_CONTENT_SIGNATURE
дела в том что я в webhook и в redirect указал одну и ту же страницу

**Comment by isorbon** [comment]
Не могу  понять где и как ошибся

**Comment by antonlva** [comment]
> Undefined index: HTTP_CONTENT_SIGNATURE

Похоже на то, что нет этой переменной в массиве. Посмотрите все содержимое $_SERVER, есть ли там такой заголовок?

**Comment by isorbon** [comment]
Да я посмотрел ) Но там нету нечего подобного и $content = file_get_contents('php://input'); контент тоже пуст

**Comment by antonlva** [comment]
А вы не путаете оюработчики редиректа после успешной оплаты, который происходит в браузере плательщика и асинхронного вебхука, который приходит от платформы? Логично, что в первом случае не будет никакого вебхука и структура будет пуста.

**Comment by isorbon** [comment]
Я делаю так :
создаю инвойс, формировываю ссылку на инвойс, и в теле ссылки указываю редирект и та же ссылка указан в веб хуке) После успешной оплаты я жду на эту редирект url данные, 
Точнее покупатель вводить свои данные перенаправляется на редирект урл и там же я жду хука

**Comment by antonlva** [comment]
Советую вам разнести эти обработчики по разным модулям и разным урлам.

**Comment by isorbon** [comment]
А веб хук я как то могу увидеть например в действия 
Я попробовал платить и оплата проходило успешно ) Но вебхук отдыхает

**Comment by avcherkasov** [comment]
https://developer.rbk.money/docs/integrations/examples/php-kkt-cart-webhooks/#2

```
<form action="https://your-web-site.address/success.action.php" method="GET">
```
`action` - это редирект на информационную страницу, вида: Ваш платеж принят. В ближайшее время с вами свяжется менеджер. И, когда к вам приходит пустой GET запрос в нем нет ничего, отсюда и `Undefined index: HTTP_CONTENT_SIGNATURE`

`success.action.php`
```
<?php
echo "Ваш платеж принят. В ближайшее время с вами свяжется менеджер";
?>
```

**Comment by avcherkasov** [comment]
Вебхук приходит в фоне POST запросом с заголовками и телом сообщения.
Это совершенно другая страница и обработчик.
Пользователь ее не видит

**Comment by isorbon** [comment]
Кстати я не использую такой формат <form action="https://your-web-site.address/success.action.php" method="GET">


а вот такой )
	return "https://checkout.rbk.money/v1/checkout.html?name=Speak25.com&description=".$row['title']."&payButtonLabel=&logo=http://speak25.com/logo1.png&email=".$email."&redirectUrl=".$redirectUrl."&popupMode=true&terminals=true&wallets=true&invoiceID=".$invoiceTemplateID."&invoiceAccessToken=".$invoiceTemplateAccessToken;

**Comment by avcherkasov** [comment]
`$redirectUrl`- значит в данном случае в `$redirectUrl` - у вас находится
```
<?php
echo "Ваш платеж принят. В ближайшее время с вами свяжется менеджер";
?>
```

**Comment by isorbon** [comment]
Спасибо огромное, уважаемые разработчики очень помогли

**Comment by isorbon** [comment]
в принципе я понял

**Comment by antonlva** [comment]
👍
