### ISSUE TITLE
400 Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by bukvy** [rbkmoney/docs#88]
When I send request with my shopid and apikey it responses with "400 Request Header Or Cookie Too Large".
When I shorten apikey  it response Unauthorized.
apikey is rather big 2100 bytes.
What to do?

**Comment by niku64** [comment]
Hello. Can you provide an URL of the request?

**Comment by bukvy** [comment]
ss77.ru/invoice.php
Support of rbkmoney proposed to increase length of  X-Request-ID, I did it till 10 characters but it did not help.

**Comment by avcherkasov** [comment]
Use url with **https** when sending request
Example: https://api.rbk.money/v1/processing/invoices

**Comment by bukvy** [comment]
It is turned out, that this error is issued in all problems neither connected with cookies nor large header. Problem is resolved by some scrutinize of header and changing SSL protocol level ( by upgrading OS to CentOS 7 from CentOS 6  and accordingly all modules tied with this new OS. )
