### ISSUE TITLE
Не работает форма в мобильном Safari

### ISSUE THREAD

**Issue by fat4lix** [rbkmoney/docs#89]
Добрый день!
Форма не открыватся в мобильном Safari. Использую js api.

Проблема где-то здесь:
<img width="542" alt="2018-07-27 1 34 54" src="https://user-images.githubusercontent.com/3585188/43292316-66178e2c-913d-11e8-8746-e9081755bb62.png">

Переменная t = null

**Comment by antonlva** [comment]
Такие вопросы надо напрямую в поддержку support@rbk.money кидать. Здесь тематика проекта - документация.
