### ISSUE TITLE
Ссылки на документацию не работают

### ISSUE THREAD

**Issue by loveitgroup** [rbkmoney/docs#94]
Добрый день,
https://rbkmoney.github.io/docs/ - тут ссылки на документацию с готовыми решениями или кастомными не работают.
Пожалуйста помогите найти описание как сделать собственную форму оплаты (в нашем случае это "анонимное пожертвование" - т.е. нам не нужны ни проверки, ни уведомления).

Спасибо!

**Comment by antonlva** [comment]
Да, спасибо, за репорт. Мы видели этот баг и уже пофиксили.

**Comment by antonlva** [comment]
PS. Используйте официальный урл документации https://developer.rbk.money/, также по техническим вопросам обращайтесь напрямую в support@rbk.money.
