### ISSUE TITLE
Рассмотрите возможность отправки сжатых ассетов

### ISSUE THREAD

**Issue by aol-nnov** [rbkmoney/docs#99]
например,
```
 curl -I -H "Accept-Encoding: gzip" https://checkout.rbk.money/checkout.js
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 20 Aug 2018 10:22:27 GMT
Content-Type: application/javascript
Content-Length: 52213
Connection: keep-alive
Keep-Alive: timeout=20
Last-Modified: Tue, 14 Aug 2018 16:27:48 GMT
ETag: "5b730304-cbf5"
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31536000
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: public, must-revalidate, max-age=86400
```

Сервер игнорирует `Accept-Encoding: gzip` и отправляет 50кб минифицированного жс.
Минификация, конечно, хорошо, но после gzip-а с дефолтными настройками этот же бандл немногим больше 18кб.

Мобильные пользователи оценят! :)

P.S.: не уверен, что в нужный репозиторий отправил issue, но другого подходящего не нашел.

**Comment by antonlva** [comment]
👍 Спасибо, что заметили. Это баг, поправим.

**Comment by aol-nnov** [comment]
@antonlva , с токенайзером всё так же. :)

**Comment by niku64** [comment]
Готово, включили gzip для css, js и прочей текстовой статики.
